[tasks.build]
run = "go build -o bin/promql"
sources = ['*.go', '**/*.go']
outputs = ['bin/promql']

[tasks.clean]
run = "rm -rf ./bin/promql"

[tasks."release:dry-run"]
run = "goreleaser release --clean --auto-snapshot --skip publish"

[tasks."release:publish"]
run = "goreleaser release --clean"

[tasks."release:bump"]
run = "release-it"

[tools]
"npm:release-it" = "latest"
"go:github.com/goreleaser/goreleaser" = "latest"
