# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PromqlCli < Formula
  desc "Promql commandline client for CLI Grafana"
  homepage "https://github.com/zph/promql-cli"
  version "0.3.2"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zph/promql-cli/releases/download/v0.3.2/promql-cli_darwin_x86_64.tar.gz"
      sha256 "299c058787699a91ce122954517b570021f03d572f9b7a7b57fbd1a4de8f91ec"

      def install
        bin.install "promql"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zph/promql-cli/releases/download/v0.3.2/promql-cli_darwin_arm64.tar.gz"
      sha256 "81ce5c9d5d1e9e2b2345463ec0fdac0507a8970b3c048c810d9521836e99a32a"

      def install
        bin.install "promql"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zph/promql-cli/releases/download/v0.3.2/promql-cli_linux_x86_64.tar.gz"
      sha256 "445dc249016eb8e8b874e9ec136f9fdc54cea5d5a9854070a72a15bf0f406479"

      def install
        bin.install "promql"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zph/promql-cli/releases/download/v0.3.2/promql-cli_linux_arm64.tar.gz"
      sha256 "89025fcc50cd9830e2f121e4f18ebb7494d3d61216701ac58c8f3607c6c324d0"

      def install
        bin.install "promql"
      end
    end
  end

  head "https://github.com/zph/promql-cli.git"

  test do
    system "#{bin}/promql --version"
  end
end
