# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class PromqlCli < Formula
  desc "Promql commandline client for CLI Grafana"
  homepage "https://github.com/zph/promql-cli"
  version "0.3.1"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/zph/promql-cli/releases/download/v0.3.1/promql-cli_darwin_x86_64.tar.gz"
      sha256 "91a64a350ed2d9384e29c869ec477bba9a63fdb41d56bb9cc7cfa563dfa50908"

      def install
        bin.install "promql-cli"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/zph/promql-cli/releases/download/v0.3.1/promql-cli_darwin_arm64.tar.gz"
      sha256 "56e058db64a2493e518acb13d429d43e53c621364e6aba9fad0e5450d3bf2391"

      def install
        bin.install "promql-cli"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/zph/promql-cli/releases/download/v0.3.1/promql-cli_linux_x86_64.tar.gz"
      sha256 "947b74c47a228b8cf91e26f2c28e5af645f949545f7d88f73c4825dafed1b29e"

      def install
        bin.install "promql-cli"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/zph/promql-cli/releases/download/v0.3.1/promql-cli_linux_arm64.tar.gz"
      sha256 "288c2a7ed0af86d5e8805442a38ac25da9508e664c71bc26ed04cfb52b915ac9"

      def install
        bin.install "promql-cli"
      end
    end
  end

  head "https://github.com/zph/promql-cli.git"

  test do
    system "#{bin}/promql --version"
  end
end
